#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : meson
Version  : 0.59.0
Release  : 301
URL      : file:///aot/build/clearlinux/packages/meson/meson-v0.59.0.tar.gz
Source0  : file:///aot/build/clearlinux/packages/meson/meson-v0.59.0.tar.gz
Summary  : A high performance build system
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0
Requires: meson-bin = %{version}-%{release}
Requires: meson-data = %{version}-%{release}
Requires: meson-man = %{version}-%{release}
Requires: meson-python = %{version}-%{release}
Requires: meson-python3 = %{version}-%{release}
Requires: mypy
Requires: ninja
Requires: tqdm
Requires: typing_extensions
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-meson
BuildRequires : mypy
BuildRequires : ninja
BuildRequires : pep517
BuildRequires : python-build
BuildRequires : tqdm
BuildRequires : typing_extensions
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
ftdetect sets the filetype
ftplugin sets Meson indentation rules
indent does Meson indentation
syntax does Meson syntax highlighting

%package bin
Summary: bin components for the meson package.
Group: Binaries
Requires: meson-data = %{version}-%{release}

%description bin
bin components for the meson package.


%package data
Summary: data components for the meson package.
Group: Data

%description data
data components for the meson package.


%package man
Summary: man components for the meson package.
Group: Default

%description man
man components for the meson package.


%package python
Summary: python components for the meson package.
Group: Default
Requires: meson-python3 = %{version}-%{release}

%description python
python components for the meson package.


%package python3
Summary: python3 components for the meson package.
Group: Default
Requires: python3-core
Provides: pypi(meson)

%description python3
python3 components for the meson package.


%prep
%setup -q -n meson
cd %{_builddir}/meson

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1629520264
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=16 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=16 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=16 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=16 "
export MAKEFLAGS=%{?_smp_mflags}
if [ ! -f setup.py ]; then
printf "#!/usr/bin/env python\nfrom setuptools import setup\nsetup()" > setup.py
chmod +x setup.py
python3 setup.py build
else
python3 setup.py build
fi

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
## install_append content
# install syntax highlight files for vim
install -dm 0755 %{buildroot}/usr/share/vim/vim82/{ftdetect,ftplugin,indent,syntax}
install -m0644 ./data/syntax-highlighting/vim/ftdetect/*   %{buildroot}/usr/share/vim/vim82/ftdetect/
install -m0644 ./data/syntax-highlighting/vim/ftplugin/*   %{buildroot}/usr/share/vim/vim82/ftplugin/
install -m0644 ./data/syntax-highlighting/vim/indent/*     %{buildroot}/usr/share/vim/vim82/indent/
install -m0644 ./data/syntax-highlighting/vim/syntax/*     %{buildroot}/usr/share/vim/vim82/syntax/
# syntax highlight for nvim
install -dm 0755 %{buildroot}/usr/share/nvim/runtime/{ftplugin,indent,syntax}
install -m0644 ./data/syntax-highlighting/vim/ftplugin/*   %{buildroot}/usr/share/nvim/runtime/ftplugin/
install -m0644 ./data/syntax-highlighting/vim/indent/*     %{buildroot}/usr/share/nvim/runtime/indent/
install -m0644 ./data/syntax-highlighting/vim/syntax/*     %{buildroot}/usr/share/nvim/runtime/syntax/
# syntax highlight for emacs
install -dm 0755 %{buildroot}/usr/share/emacs/site-lisp
install -m0644 ./data/syntax-highlighting/emacs/*          %{buildroot}/usr/share/emacs/site-lisp/
# shell completion for bash
install -dm 0755 %{buildroot}/usr/share/bash-completion/completions
install -m0644 ./data/shell-completions/bash/*             %{buildroot}/usr/share/bash-completion/completions/
# shell completions for zsh
install -dm 0755 %{buildroot}/usr/share/zsh/site-functions
install -m0644 ./data/shell-completions/zsh/*              %{buildroot}/usr/share/zsh/site-functions/
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/meson

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/meson
/usr/share/emacs/site-lisp/meson.el
/usr/share/nvim/runtime/ftplugin/meson.vim
/usr/share/nvim/runtime/indent/meson.vim
/usr/share/nvim/runtime/syntax/meson.vim
/usr/share/polkit-1/actions/com.mesonbuild.install.policy
/usr/share/vim/vim82/ftdetect/meson.vim
/usr/share/vim/vim82/ftplugin/meson.vim
/usr/share/vim/vim82/indent/meson.vim
/usr/share/vim/vim82/syntax/meson.vim
/usr/share/zsh/site-functions/_meson

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/meson.1

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
